export const periodPopDetail = [
  // {'vc_fundname': 'yertyhert'},
  // {'vc_fundname': 'tyhrtyertyert'},
  // {'vc_fundname': 'yert'},
  // {'vc_fundname': 'gfhdfghdfg'},
  // {'vc_fundname': 'hdfgh'},
  // {'vc_fundname': 'tyhrtyertyert'},
  // // {'vc_fundname': 'dhftghfgh'},
  // {'vc_fundname': 'jgh'},
  // {'vc_fundname': 'dfhgdf'},
  // {'vc_fundname': 'hgjghdgfh'},
  // {'vc_fundname': 'tyhrtyertyert'},
  // {'vc_fundname': 'dhftghfgh'},
  // {'vc_fundname': 'jgh'},
  // {'vc_fundname': 'dfhgdf'},
  // {'vc_fundname': 'hgjghdgfh'},
  {'vc_fundname': '1-tyhrtyertyert'},
  {'vc_fundname': '2-dhftghfgh'},
  {'vc_fundname': '3-jgh'},
  {'vc_fundname': '4-dfhgdf'},
  {'vc_fundname': '5-hgjghdgfh'},
  {'vc_fundname': '6-tyhrtyertyert'},
  {'vc_fundname': '7-dhftghfgh'},
  {'vc_fundname': '8-jgh'},
  {'vc_fundname': '9-dfhgdf'},
  {'vc_fundname': '10-hgjghdgfh'},
  {'vc_fundname': '11-tyhrtyert'},
  {'vc_fundname': '12-tyhrtyerdhtyert'},
  {'vc_fundname': '13-jgh'},
  {'vc_fundname': '14-dfhgdf'},
  {'vc_fundname': '15-hgjghdgfh'},
  {'vc_fundname': '16-tyhrtyert'},
  {'vc_fundname': '17-tyhrtyerdhtyert'},
  {'vc_fundname': '18-jgh'},
  {'vc_fundname': '19-dfhgdf'},
  {'vc_fundname': '20-hgjghdgfh'},
  {'vc_fundname': '21-tyhrtyert'},
  {'vc_fundname': '22-tyhrtyerdhtyert'},
  {'vc_fundname': '23-jgh'},
  {'vc_fundname': '24-dfhgdf'},
  {'vc_fundname': '25-hgjghdgfh'},
  {'vc_fundname': '26-tyhrtyert'},
  {'vc_fundname': '27-tyhrtyerdhtyert'},
  {'vc_fundname': '28-jgh'},
  {'vc_fundname': '29-dfhgdf'},
  {'vc_fundname': '20-hgjghdgfh'},
  {'vc_fundname': '21-tyhrtyert'},
  {'vc_fundname': '22-tyhrtyerdhtyert'},
  {'vc_fundname': '23-jgh'},
  {'vc_fundname': '24-dfhgdf'},
  {'vc_fundname': '25-hgjghdgfh'},
  {'vc_fundname': '26-tyhrtyert'},
  {'vc_fundname': '27-tyhrtyerdhtyert'},
  {'vc_fundname': '28-jgh'},
  {'vc_fundname': '29-dfhgdf'},
  {'vc_fundname': '30-dfhgdf'},
  {'vc_fundname': '31-tyhrtyert'},
  {'vc_fundname': '32-tyhrtyerdhtyert'},
  {'vc_fundname': '33-jgh'},
  {'vc_fundname': '34-dfhgdf'},
  {'vc_fundname': '35-hgjghdgfh'},
  {'vc_fundname': '36-tyhrtyert'},
  {'vc_fundname': '37-tyhrtyerdhtyert'},
  {'vc_fundname': '38-jgh'},
  {'vc_fundname': '39-dfhgdf'},
  {'vc_fundname': '1-tyhrtyertyert'},
  {'vc_fundname': '2-dhftghfgh'},
  {'vc_fundname': '3-jgh'},
  {'vc_fundname': '4-dfhgdf'},
  {'vc_fundname': '5-hgjghdgfh'},
  {'vc_fundname': '6-tyhrtyertyert'},
  {'vc_fundname': '7-dhftghfgh'},
  {'vc_fundname': '8-jgh'},
  {'vc_fundname': '9-dfhgdf'},
  {'vc_fundname': '10-hgjghdgfh'},
  {'vc_fundname': '11-tyhrtyert'},
  {'vc_fundname': '12-tyhrtyerdhtyert'},
  {'vc_fundname': '13-jgh'},
  {'vc_fundname': '14-dfhgdf'},
  {'vc_fundname': '15-hgjghdgfh'},
  {'vc_fundname': '16-tyhrtyert'},
  {'vc_fundname': '17-tyhrtyerdhtyert'},
  {'vc_fundname': '18-jgh'},
  {'vc_fundname': '19-dfhgdf'},
  {'vc_fundname': '20-hgjghdgfh'},
  {'vc_fundname': '21-tyhrtyert'},
  {'vc_fundname': '22-tyhrtyerdhtyert'},
  {'vc_fundname': '23-jgh'},
  {'vc_fundname': '24-dfhgdf'},
  {'vc_fundname': '25-hgjghdgfh'},
  {'vc_fundname': '26-tyhrtyert'},
  {'vc_fundname': '27-tyhrtyerdhtyert'},
  {'vc_fundname': '28-jgh'},
  {'vc_fundname': '29-dfhgdf'},
  {'vc_fundname': '20-hgjghdgfh'},
  {'vc_fundname': '21-tyhrtyert'},
  {'vc_fundname': '22-tyhrtyerdhtyert'},
  {'vc_fundname': '23-jgh'},
  {'vc_fundname': '24-dfhgdf'},
  {'vc_fundname': '25-hgjghdgfh'},
  {'vc_fundname': '26-tyhrtyert'},
  {'vc_fundname': '27-tyhrtyerdhtyert'},
  {'vc_fundname': '28-jgh'},
  {'vc_fundname': '29-dfhgdf'},
  {'vc_fundname': '30-dfhgdf'},
  {'vc_fundname': '31-tyhrtyert'},
  {'vc_fundname': '32-tyhrtyerdhtyert'},
  {'vc_fundname': '33-jgh'},
  {'vc_fundname': '34-dfhgdf'},
  {'vc_fundname': '35-hgjghdgfh'},
  {'vc_fundname': '36-tyhrtyert'},
  {'vc_fundname': '37-tyhrtyerdhtyert'},
  {'vc_fundname': '37-tyhrtyerdhtyert'},
  {'vc_fundname': '37-tyhrtyerdhtyert'},
  {'vc_fundname': '32-tyhrtyerdhtyert'},
  {'vc_fundname': '33-jgh'},
  {'vc_fundname': '34-dfhgdf'},
  {'vc_fundname': '35-hgjghdgfh'},
  {'vc_fundname': '36-tyhrtyert'},
  {'vc_fundname': '38-jgh'},
  {'vc_fundname': '32-tyhrtyerdhtyert'},
  {'vc_fundname': '33-jgh'},
  {'vc_fundname': '34-dfhgdf'},
  {'vc_fundname': '35-hgjghdgfh'},
  {'vc_fundname': '36-tyhrtyert'},
  {'vc_fundname': '37-tyhrtyerdhtyert'},
  {'vc_fundname': '38-jgh'},
  {'vc_fundname': '39-dfhgdf'},
  {'vc_fundname': '39-dfhgdf'},
  {'vc_fundname': '35-hgjghdgfh'},
  {'vc_fundname': '36-tyhrtyert'},
  {'vc_fundname': '37-tyhrtyerdhtyert'},
  {'vc_fundname': '38-jgh'},
  {'vc_fundname': '39-dfhgdf'},
  {'vc_fundname': '39-dfhgdf'},
  {'vc_fundname': '39-dfhgdf'},
  {'vc_fundname': '34-dfhgdf'},
  {'vc_fundname': '35-hgjghdgfh'},
  {'vc_fundname': '36-tyhrtyert'},
  {'vc_fundname': '37-tyhrtyerdhtyert'},
  {'vc_fundname': '38-jgh'},
  {'vc_fundname': '39-dfhgdf'},
  {'vc_fundname': '39-dfhgdf'},
  {'vc_fundname': '39-dfhgdf'},
]
export const periodIncome = [
  // {'vc_fundcode': '1-sdaeswfadfghfghfewsf'},
  // {'vc_fundcode': '2-sdaeswfaehdftgfwsf'},
  // {'vc_fundcode': '3-sdaeswfadfghfewsf'},
  // {'vc_fundcode': '4-sdaeswfdfghgffhdaewsf'},
  // {'vc_fundcode': '5-sdaeswfadhfghfghfdgewsf'},
  // {'vc_fundcode': '6-sdaeswfdhfghfgaewsf'},
  // {'vc_fundcode': '7-sdaeswhdfghfghfdghdfghfaewsf'},
  // {'vc_fundcode': '8-sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': '9-sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': '10-sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': '11-sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': '12-sdaeswfdhfghfgaewsf'},
  {'vc_fundcode': '13-sdaeswhdfghfghfdghdfghfaewsf'},
  {'vc_fundcode': '14-sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': '15-sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': '16-sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': '17-sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': '18-sdaeswfdhfghfgaewsf'},
  {'vc_fundcode': '19-sdaeswhdfghfghfdghdfghfaewsf'},
  {'vc_fundcode': '20-sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': '21-sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': '22-sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': '23-sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': '24-sdaeswfdhfghfgaewsf'},
  {'vc_fundcode': '25-sdaeswhdfghfghfdghdfghfaewsf'},
  {'vc_fundcode': '26-sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': '27-sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': '28-sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': '29-sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': '30-sdaeswfdhfghfgaewsf'},
  {'vc_fundcode': '31-sdaeswhdfghfghfdghdfghfaewsf'},
  // {'vc_fundcode': '32-sdaeswfdfghgffhdaewsf'},
  // {'vc_fundcode': '33-sdaeswfadhfghfghfdgewsf'},
  // {'vc_fundcode': '34-sdaeswfdhfghfgaewsf'},
  // {'vc_fundcode': '35-sdaeswhdfghfghfdghdfghfaewsf'}
]
 export const hisIncome = [
  {'vc_fundcode': '1-dsfghdd'},
  {'vc_fundcode': '2-dsfd'},
  {'vc_fundcode': '3-dshdfghffd'},
  {'vc_fundcode': '4-dsffgdhfgd'},
  {'vc_fundcode': '5-dsfd'},
  {'vc_fundcode': '6-dshdfghffd'},
  // {'vc_fundcode': '7-dsffgdhfgd'},
  // {'vc_fundcode': '8-dsfd'},
  // {'vc_fundcode': '9-dsfd'},
  {'vc_fundcode': '10-dshdfghffd'},
  {'vc_fundcode': '21-dsffgdhfgd'},
  {'vc_fundcode': '22-dsfd'},
  {'vc_fundcode': '23-dshdfghffd'},
  {'vc_fundcode': '24-dsffgdhfgd'},
  {'vc_fundcode': '25-dsfd'},
  {'vc_fundcode': '26-dsfd'},
  {'vc_fundcode': '27-dshdfghffd'},
  {'vc_fundcode': '28-dsffgdhfgd'},
  {'vc_fundcode': '29-dsfd'},
  {'vc_fundcode': '30-dsfd'},
  {'vc_fundcode': '31-dshdfghffd'},
  {'vc_fundcode': '32-dsffgdhfgd'},
  {'vc_fundcode': '33-dsfd'},
  {'vc_fundcode': '34-dsfd'},
  {'vc_fundcode': '35-dshdfghffd'},
  {'vc_fundcode': '36-dsffgdhfgd'},
  {'vc_fundcode': '37-dsfd'},
  {'vc_fundcode': '38-dshdfghffd'},
  {'vc_fundcode': '39-dsffgdhfgd'},
  {'vc_fundcode': '40-dsfd'},
  {'vc_fundcode': '41-dsfd'},
  {'vc_fundcode': '42-dshdfghffd'},
  {'vc_fundcode': '43-dsffgdhfgd'},
  {'vc_fundcode': '44-dsfd'},
  {'vc_fundcode': '45-dshdfghffd'},
  {'vc_fundcode': '46-dsffgdhfgd'},
  {'vc_fundcode': '47-dsfd'},
  {'vc_fundcode': '48-dsfd'},
  {'vc_fundcode': '49-dshdfghffd'},
  {'vc_fundcode': '51-dsffgdhfgd'},
  {'vc_fundcode': '52-dsfd'},
  {'vc_fundcode': '53-dshdfghffd'},
  {'vc_fundcode': '54-dsffgdhfgd'},
  // {'vc_fundcode': '55-dsfd'},
  // {'vc_fundcode': '56-dsfd'},
  // {'vc_fundcode': '57-dshdfghffd'},
  // {'vc_fundcode': '58-dsffgdhfgd'},
  // {'vc_fundcode': '59-dsfd'},
  // {'vc_fundcode': '60-dsfd'},
  // {'vc_fundcode': '61-dshdfghffd'},
  // {'vc_fundcode': '62-dsffgdhfgd'},
  // {'vc_fundcode': '63-dsfd'},
  // {'vc_fundcode': '64-dshdfghffd'},
  // {'vc_fundcode': '65-dsffgdhfgd'},
  // {'vc_fundcode': '66-dsfhfgdhfghgfd'},
  {'vc_fundcode': '67-dsfdfghdfgh'}
]
 export const dealRecord = [
  // {'fundName': 'rygrshyyty'},
  // {'fundName': 'rygrsthy'},
  // {'fundName': 'rygrsertyftdftytfyftty'},
  // {'fundName': 'rygrsthgfhfghy'},
  // {'fundName': 'rygrsdfghfgty'},
  // {'fundName': 'rygrshyyty'},
  // {'fundName': 'rygrsthy'},
  // {'fundName': 'rygrsertyftdftytfyftty'},
  // {'fundName': 'rygrsthgfhfghy'},
  // {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  // {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  // {'fundName': 'rygrsdfghfgty'},
  // {'fundName': 'rygrshyyty'},
  // {'fundName': 'rygrsthy'},
  // {'fundName': 'rygrsertyftdftytfyftty'},
  // {'fundName': 'rygrsthgfhfghy'},
  // {'fundName': 'rygrsdfghfgty'},
  // {'fundName': 'rygrshyyty'},
  // {'fundName': 'rygrsthy'},
  // {'fundName': 'rygrsertyftdftytfyftty'},
  // {'fundName': 'rygrsthgfhfghy'},
  // {'fundName': 'rygrsdfghfgty'},
  // {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshfghfdghty'}
]
export const  rateDes = "注：持仓比例中美元资产已兑换人民币计算，汇率为："

export const pieOption  = {
  color:['#187FC3','#CF121B','#5173A5'],
  backgroundColor:'#FFFFFF',
  series: [
    {
      name: '访问来源',
      type: 'pie',
      radius: ['50%', '70%'],
      avoidLabelOverlap: false,
      animation: false,
      label: {
        formatter: '{b}: {c} ({d}%)',
        position: 'outer',
        alignTo: 'labelLine',
        bleedMargin: 5
      },
      data:  [
        {value: 44, name: '类固收'},
        {value: 55, name: '净值型'},
        {value: 77, name: '股权类'}
      ]
    }
  ]
}