export const periodPopDetailData = [


  {'vc_fundname': 'ghrth'},
  {'vc_fundname': 'tyhrtyertyert'},
  {'vc_fundname': 'yertyhert'},
  {'vc_fundname': 'tyhrtyertyert'},
  {'vc_fundname': 'yert'},
  {'vc_fundname': 'gfhdfghdfg'},
  {'vc_fundname': 'hdfgh'},

  {'vc_fundname': 'ghrth'},
  {'vc_fundname': 'tyhrtyertyert'},
  {'vc_fundname': 'yertyhert'},
  {'vc_fundname': 'tyhrtyertyert'},
  {'vc_fundname': 'yert'},
  {'vc_fundname': 'gfhdfghdfg'},
  {'vc_fundname': 'hdfgh'},
  {'vc_fundname': 'tyhrtyertyert'},
  {'vc_fundname': 'dhftghfgh'},
  {'vc_fundname': 'jgh'},
  {'vc_fundname': 'dfhgdf'},
  {'vc_fundname': 'hgjghdgfh'},
  {'vc_fundname': 'tyhrtyertdhfghfdgdhyert'},
  {'vc_fundname': 'tyhrtyerdhtyert'}
]
export const periodIncomeData = [

  {'vc_fundcode': 'sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': 'sdaeswfdhfghfgaewsf'},
  {'vc_fundcode': 'sdaeswhdfghfghfdghdfghfaewsf'},{'vc_fundcode': 'sdaeswfadfghfghfewsf'},
  {'vc_fundcode': 'sdaeswfaehdftgfwsf'},
  {'vc_fundcode': 'sdaeswfadfghfewsf'},

  {'vc_fundcode': 'sdaeswfadhfghfghfdgewsf'},


  {'vc_fundcode': 'sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': 'sdaeswfaehdftgfwsf'},
  {'vc_fundcode': 'sdaeswfadfghfewsf'},
  {'vc_fundcode': 'sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': 'sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': 'sdaeswfdhfghfgaewsf'},
  {'vc_fundcode': 'sdaeswhdfghfghfdghdfghfaewsf'},{'vc_fundcode': 'sdaeswfadfghfghfewsf'},
  {'vc_fundcode': 'sdaeswfaehdftgfwsf'},
  {'vc_fundcode': 'sdaeswfadfghfewsf'},
  {'vc_fundcode': 'sdaeswfdfghgffhdaewsf'},
  {'vc_fundcode': 'sdaeswfadhfghfghfdgewsf'},
  {'vc_fundcode': 'sdaeswfdhfghfgaewsf'},
  {'vc_fundcode': 'sdaeswhdfghfghfdghdfghfaewsf'}
]
export const hisIncomeData = [
  {'vc_fundcode': 'dsfghdd'},
  {'vc_fundcode': 'dsfd'},
  {'vc_fundcode': 'dshdfghffd'},
  {'vc_fundcode': 'dsffgdhfgd'},
  {'vc_fundcode': 'dsfhfgdhfghgfd'},
  {'vc_fundcode': 'dsfghdd'},
  {'vc_fundcode': 'dsfd'},
  {'vc_fundcode': 'dshdfghffd'},
  {'vc_fundcode': 'dsffgdhfgd'},
  {'vc_fundcode': 'dsfhfgdhfghgfd'},
  {'vc_fundcode': 'dsfghdd'},
  {'vc_fundcode': 'dsfd'},
  {'vc_fundcode': 'dshdfghffd'},
  {'vc_fundcode': 'dsffgdhfgd'},
  {'vc_fundcode': 'dsfhfgdhfghgfd'},
  {'vc_fundcode': 'dsfghdd'},
  {'vc_fundcode': 'dsfd'},
  {'vc_fundcode': 'dshdfghffd'},
  {'vc_fundcode': 'dsffgdhfgd'},
  {'vc_fundcode': 'dsfhfgdhfghgfd'}, {'vc_fundcode': 'dsfghdd'},
  {'vc_fundcode': 'dsfd'},
  {'vc_fundcode': 'dshdfghffd'},
  {'vc_fundcode': 'dsffgdhfgd'},
  {'vc_fundcode': 'dsfhfgdhfghgfd'},
  {'vc_fundcode': 'dsfdfghdfgh'}
]
export const  dealRecordData = [
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshyyty'},
  {'fundName': 'rygrsthy'},
  {'fundName': 'rygrsertyftdftytfyftty'},
  {'fundName': 'rygrsthgfhfghy'},
  {'fundName': 'rygrsdfghfgty'},
  {'fundName': 'rygrshfghfdghty'}
]
